site_name: IDEAS DGGS R Rendering documentations
repo_name: thespatiallabatLaurier/dggslayer
repo_url: https://github.com/thespatiallabatLaurier/dggslayer
theme: 
  name: readthedocs
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - instant

copyright: Copyright &copy; 2019 - 2020 TheSpatiallab
